version: '2'
services:
  jhipsterexample-app:
    image: jhipsterexample
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://jhipsterexample-mssql:1433;database=jhipsterexample
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 9090:9090
  jhipsterexample-mssql:
    extends:
      file: mssql.yml
      service: jhipsterexample-mssql
